name: "SunGather"
version: "0.1.2"
slug: sungather
description: "Extract Sungrow data from local Inverter"
arch: 
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
url: "https://github.com/bohdan-s/SunGather"
startup: application
ingress: true
ingress_port: 8099
boot: auto
discovery:
  - "mqtt"
services:
  - "mqtt:need"
map: 
  - share:rw
options: 
  host: 192.168.1.100
  timeout: 10
  scan_interval: 30
  connection: "modbus"
  smart_meter: True
  custom_mqtt_server: False
  log_console: "INFO"
schema:
  host: str
  timeout: int(3,60)?
  scan_interval: int(5,600)?
  connection: "list(sungrow|modbus|http)"
  smart_meter: bool
  custom_mqtt_server: bool
  log_console: "list(OFF|INFO|WARNING|ERROR|DEBUG)?"
panel_icon: mdi:SolarPowerVariant
init: false





